

const katalog = [
    {
        id: 1,
        naziv: 'BASIC CHIC crna',
        cena: 1890,
        slika: ['/crna.webp', '/crna1.webp', '/crna2.webp', '/crna3.webp'],
        opis: 'Basic Chic bluza izrađena je od visokokvalitetne duo mrežice koja se rasteže u oba pravca, prilagođava telu i ne sputava pokret.',
        boja: ['Roze', 'Braon', 'Crna', 'Bordo', 'Zelena', 'Bela'],
        velicina: ['UNI'],
    },
    {
        id: 2,
        naziv: 'BASIC CHIC roze',
        cena: 1890,
        slika: ['/roze.webp', '/roze1.webp', '/roze2.webp'],
        opis: 'Basic Chic bluza izrađena je od visokokvalitetne duo mrežice koja se rasteže u oba pravca, prilagođava telu i ne sputava pokret.',
        boja: ['Roze', 'Braon', 'Crna', 'Bordo', 'Zelena', 'Bela'],
        velicina: ['UNI'],
    },
    {
        id: 3,
        naziv: 'BASIC CHIC zelena',
        cena: 1890,
        slika: ['/zelenaBluza3.webp', '/zelenaBluza4.webp'],
        opis: 'Basic Chic bluza izrađena je od visokokvalitetne duo mrežice koja se rasteže u oba pravca, prilagođava telu i ne sputava pokret.',
        boja: ['Roze', 'Braon', 'Crna', 'Bordo', 'Zelena', 'Bela'],
        velicina: ['UNI'],
    },
    {
        id: 4,
        naziv: 'BASIC CHIC bela sa rolkom',
        cena: 1890,
        slika: ['/belichic.webp', '/belichic.webp'],
        opis: 'Basic Chic bluza izrađena je od visokokvalitetne duo mrežice koja se rasteže u oba pravca, prilagođava telu i ne sputava pokret.',
        boja: ['Roze', 'Braon', 'Crna', 'Bordo', 'Zelena', 'Bela'],
        velicina: ['UNI'],
    },
    {
        id: 5,
        naziv: 'BASIC CHIC bordo sa rolkom',
        cena: 1890,
        slika: ['/bordo.webp', '/bordo2.webp', '/bordo1.webp'],
        opis: 'Basic Chic bluza izrađena je od visokokvalitetne duo mrežice koja se rasteže u oba pravca, prilagođava telu i ne sputava pokret.',
        boja: ['Roze', 'Braon', 'Crna', 'Bordo', 'Zelena', 'Bela'],
        velicina: ['UNI'],
    },
    {
        id: 6,
        naziv: 'BASIC CHIC braon sa rolkom',
        cena: 1890,
        slika: ['/braonBluza.webp', '/braonBluza1.webp'],
        opis: 'Basic Chic bluza izrađena je od visokokvalitetne duo mrežice koja se rasteže u oba pravca, prilagođava telu i ne sputava pokret.',
        boja: ['Roze', 'Braon', 'Crna', 'Bordo', 'Zelena', 'Bela'],
        velicina: ['UNI'],
    },
    {
        id: 7,
        naziv: 'BASIC CHIC zelena sa rolkom',
        cena: 1890,
        slika: ['/zelenaBluza1.webp', '/zelenaBluza2.webp', '/zelenaBluza.webp'],
        opis: 'Basic Chic bluza izrađena je od visokokvalitetne duo mrežice koja se rasteže u oba pravca, prilagođava telu i ne sputava pokret.',
        boja: ['Roze', 'Braon', 'Crna', 'Bordo', 'Zelena', 'Bela'],
        velicina: ['UNI'],
    },
    {
        id: 8,
        naziv: 'BASIC CHIC leopard print sa rolkom',
        cena: 1890,
        slika: ['/leopard.webp', '/leopard1.webp', '/leopard2.webp'],
        opis: 'Basic Chic bluza izrađena je od visokokvalitetne duo mrežice koja se rasteže u oba pravca, prilagođava telu i ne sputava pokret.',
        boja: ['Roze', 'Braon', 'Crna', 'Bordo', 'Zelena', 'Bela'],
        velicina: ['UNI'],
    },
    {
        id: 9,
        naziv: 'BASIC CHIC crna sa rolkom',
        cena: 1890,
        slika: ['/crna4.webp', '/crna5.webp'],
        opis: 'Basic Chic bluza izrađena je od visokokvalitetne duo mrežice koja se rasteže u oba pravca, prilagođava telu i ne sputava pokret.',
        boja: ['Roze', 'Braon', 'Crna', 'Bordo', 'Zelena', 'Bela'],
        velicina: ['UNI'],
    },
    {
        id: 10,
        naziv: 'BASIC CHIC leopard print',
        cena: 2100,
        slika: ['/leopardPrint2.webp', '/leopardPrint1.webp'],
        opis: 'Basic Chic leopard print izrađena je od visokokvalitetne duo mrežice koja se rasteže u oba pravca, prilagođava telu i ne sputava pokret.',
        boja: ['Leopard print'],
        velicina: ['UNI'],
    },
    {
        id: 11,
        naziv: 'KOKKO FLORAL haljina',
        cena: 5290,
        slika: ['/flowersHaljina.webp', '/flowersHaljina1.webp'],
        opis: 'Haljina dugih rukava, pripijeni kroj koji prati liniju tela, rastegljiv materijal, moze se raditi i sa postavom i bez postave, ukoliko želite da je nosite na plažu.',
        boja: ['Flower'],
        velicina: ['UNI'],
    },
    {
        id: 12,
        naziv: 'WHISPER',
        cena: 2900,
        slika: ['/whisper1.webp', '/whisper.webp'],
        opis: 'WHISPER je izrađena od visokokvalitetne duo mrežice koja se rasteže u oba pravca, prilagođava telu i ne sputava pokret.',
        boja: ['Roze', 'Braon', 'Crna', 'Bordo', 'Zelena', 'Bela'],
        velicina: ['UNI'],
    }

]


export default katalog;